export const sentences: string[] = [
    "Kamień, papier, nożyce - prosty wybór, ale trudne wygrane.",
    "Gra w papier, nożyce, kamień - nieskończone kombinacje, nieskończona zabawa.",
    "W papier, nożyce, kamień nie zawsze chodzi o wygraną, ale o emocje, które daje gra.",
    "Czasem nawet losowa decyzja w papier, nożyce, kamień może zmienić losy.",
    "W grze papier, nożyce, kamień kluczem do sukcesu jest zaskoczenie przeciwnika.",
    "Zwycięstwo w papier, nożyce, kamień - to nie tylko szczęście, ale też intuicja.",
    "W papier, nożyce, kamień trzeba być gotowym na każdą ewentualność.",
    "Papier, nożyce, kamień - gra na przypadek, ale wciąż wciągająca.",
    "W papier, nożyce, kamień warto podjąć ryzyko, by osiągnąć sukces.",
    "Nie ma jednej słusznej strategii w papier, nożyce, kamień - trzeba improwizować.",
    "W papier, nożyce, kamień nie ważne, czy wygrasz czy przegrasz, ważne, że grasz.",
    "Czasem najprostsze gry, jak papier, nożyce, kamień, dają najwięcej radości.",
    "Kamień, papier, nożyce - jak życie, pełne niespodziewanych zwrotów akcji.",
    "W papier, nożyce, kamień trzeba być elastycznym i dostosowywać się do sytuacji.",
    "Papier, nożyce, kamień - gdzie decyzje podejmowane w sekundę mają znaczenie.",
    "Kamień, papier, nożyce - kiedy zasady gry są proste, ale emocje skomplikowane.",
    "W grze papier, nożyce, kamień potrzebna jest koncentracja i spostrzegawczość.",
    "Gra w papier, nożyce, kamień uczy nas szacunku dla różnorodności wyborów.",
    "Nie chodzi tylko o to, co wybierzesz w papier, nożyce, kamień, ale jak zareagujesz na wynik.",
    "W papier, nożyce, kamień ważne jest, aby mieć zimną krew i nie dać się zwieść emocjom.",
    "Kamień, papier, nożyce - gra, która łączy pokolenia i kultury.",
    "W papier, nożyce, kamień można odnaleźć strategię w chaosie.",
    "W papier, nożyce, kamień najlepsza obrona to atak.",
    "W papier, nożyce, kamień kluczem do wygranej jest przewidywanie ruchów przeciwnika.",
    "W grze papier, nożyce, kamień czasem warto ryzykować, by osiągnąć cel.",
    "Papier, nożyce, kamień - gra, która łączy ludzi i wzmacnia więzi.",
    "W papier, nożyce, kamień zwycięzcy mają zawsze ostatnie słowo.",
    "Gra w papier, nożyce, kamień pokazuje, że czasem najprostsze rozwiązania są najlepsze.",
    "Nie ma przegranych w papier, nożyce, kamień, są tylko kolejne szanse.",
    "W grze papier, nożyce, kamień kluczem do sukcesu jest zachowanie tajemnicy.",
    "Papier, nożyce, kamień - gra, która nie wymaga specjalnych umiejętności, ale może dostarczyć dużo frajdy.",
    "W papier, nożyce, kamień warto pamiętać, że czasem los decyduje o wyniku.",
    "Kamień, papier, nożyce - gra, która wymaga umiejętności przewidywania.",
    "W grze papier, nożyce, kamień chodzi o szybkie myślenie i bycie o krok do przodu.",
    "W papier, nożyce, kamień każda decyzja ma znaczenie, nawet ta najmniejsza.",
    "Nie zawsze w papier, nożyce, kamień chodzi o wygraną, ale o dobrą zabawę.",
    "Papier, nożyce, kamień - gra, która pokazuje, że czasem najprostsze wybory mają największy wpływ.",
    "W papier, nożyce, kamień decyzje trzeba podejmować szybko, ale rozważnie.",
    "Kamień, papier, nożyce - gra, która uczy cierpliwości i konsekwencji.",
    "W papier, nożyce, kamień wygrana zależy od umiejętności i odrobiny szczęścia.",
    "Papier, nożyce, kamień - prosty test reakcji i kreatywności.",
    "W grze papier, nożyce, kamień sztuka polega na zagrania przeciwnika.",
    "Kamień, papier, nożyce - kiedy los jest w twoich rękach.",
    "W papier, nożyce, kamień kluczowe są zręczność i pomysłowość.",
    "Papier, nożyce, kamień - nie trzeba być mistrzem strategii, by dobrze się bawić.",
    "W grze papier, nożyce, kamień czasem warto zaufać intuicji.",
    "Kamień, papier, nożyce - niewinne zabawy czasem mają największy wpływ na nasze życie.",
    "W papier, nożyce, kamień warto podjąć ryzyko, by osiągnąć wyższe cele.",
    "Gra w papier, nożyce, kamień pokazuje, że czasem trzeba iść pod prąd.",
    "Papier, nożyce, kamień - gra, która zachwyca prostotą i emocjami."
  ];
  
  