export const sentences: string[] = [
  "Rock, paper, scissors - a simple choice but challenging victories.",
  "Playing rock, paper, scissors - infinite combinations, endless fun.",
  "In rock, paper, scissors, it's not always about winning, but the emotions the game brings.",
  "Sometimes even a random decision in rock, paper, scissors can change fates.",
  "In the game of rock, paper, scissors, surprising your opponent is the key to success.",
  "Victory in rock, paper, scissors - it's not just luck, but also intuition.",
  "In rock, paper, scissors, you have to be ready for any eventuality.",
  "Rock, paper, scissors - a game of chance, but still captivating.",
  "In rock, paper, scissors, it's worth taking risks to achieve success.",
  "There is no one right strategy in rock, paper, scissors - you have to improvise.",
  "In rock, paper, scissors, it doesn't matter if you win or lose, what matters is that you play.",
  "Sometimes the simplest games, like rock, paper, scissors, bring the most joy.",
  "Rock, paper, scissors - like life, full of unexpected twists.",
  "In rock, paper, scissors, you need to be flexible and adapt to the situation.",
  "Rock, paper, scissors - where decisions made in a second matter.",
  "Rock, paper, scissors - when the rules of the game are simple but the emotions are complex.",
  "In the game of rock, paper, scissors, concentration and observation are necessary.",
  "Playing rock, paper, scissors teaches us to respect the diversity of choices.",
  "It's not just about what you choose in rock, paper, scissors, but how you react to the result.",
  "In rock, paper, scissors, it's important to keep a cool head and not be swayed by emotions.",
  "Rock, paper, scissors - a game that connects generations and cultures.",
  "In rock, paper, scissors, you can find a strategy in chaos.",
  "In rock, paper, scissors, the best defense is offense.",
  "In rock, paper, scissors, predicting your opponent's moves is the key to victory.",
  "In the game of rock, paper, scissors, sometimes it's worth taking risks to achieve your goal.",
  "Rock, paper, scissors - a game that brings people together and strengthens bonds.",
  "In rock, paper, scissors, the winners always have the last word.",
  "Playing rock, paper, scissors shows that sometimes the simplest solutions are the best.",
  "There are no losers in rock, paper, scissors, only more chances.",
  "In the game of rock, paper, scissors, keeping a secret is key to success.",
  "Rock, paper, scissors - a game that doesn't require special skills but can provide a lot of fun.",
  "In rock, paper, scissors, remember that sometimes fate decides the outcome.",
  "Rock, paper, scissors - a game that requires the skill of prediction.",
  "In the game of rock, paper, scissors, it's about quick thinking and staying one step ahead.",
  "In rock, paper, scissors, every decision matters, even the smallest ones.",
  "It's not always about winning in rock, paper, scissors, but about having a good time.",
  "Rock, paper, scissors - a game that shows that sometimes the simplest choices have the biggest impact.",
  "In rock, paper, scissors, decisions must be made quickly but thoughtfully.",
  "Rock, paper, scissors - a game that teaches patience and consistency.",
  "In rock, paper, scissors, winning depends on skill and a bit of luck.",
  "Rock, paper, scissors - a simple test of reaction and creativity.",
  "In the game of rock, paper, scissors, the art is in countering your opponent's move.",
  "Rock, paper, scissors - when fate is in your hands.",
  "In rock, paper, scissors, dexterity and resourcefulness are crucial.",
  "Rock, paper, scissors - you don't need to be a master strategist to have a good time.",
  "In the game of rock, paper, scissors, sometimes it's worth trusting your intuition.",
  "Rock, paper, scissors - innocent games sometimes have the greatest impact on our lives.",
  "In rock, paper, scissors, it's worth taking risks to achieve higher goals.",
  "Playing rock, paper, scissors shows that sometimes you need to go against the flow.",
  "Rock, paper, scissors - a game that delights in simplicity and emotions."
];
